tlmgr install pgf
tlmgr install ms
tlmgr install xcolor
tlmgr install preview
tlmgr install mptopdf
tlmgr install koma-script
tlmgr install circuitikz
tlmgr install pgfopts
tlmgr install pgfplots
